-- MySQL Script generated by MySQL Workbench
-- Sat Jan 11 16:20:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`InDoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InDoc` (
  `idInDoc` INT NOT NULL AUTO_INCREMENT,
  `inNum` VARCHAR(45) NULL,
  `currNum` VARCHAR(45) NULL,
  `dateDc` DATE NULL,
  `descInDoc` MEDIUMTEXT NULL,
  PRIMARY KEY (`idInDoc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OutDoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OutDoc` (
  `idOutDoc` INT NOT NULL AUTO_INCREMENT,
  `numDoc` VARCHAR(45) NULL,
  `dateDc` DATE NULL,
  `descOutDoc` MEDIUMTEXT NULL,
  PRIMARY KEY (`idOutDoc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `patron` VARCHAR(45) NULL,
  `descPerson` VARCHAR(45) NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SystemTransfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SystemTransfer` (
  `idSysTransfer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `descSysTrf` MEDIUMTEXT NULL,
  PRIMARY KEY (`idSysTransfer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Abonent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Abonent` (
  `idAbonent` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `descAbonent` MEDIUMTEXT NULL,
  PRIMARY KEY (`idAbonent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DocLink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DocLink` (
  `idDocLink` INT NOT NULL AUTO_INCREMENT,
  `idDocOf` INT NULL,
  `idDocIn` INT NULL,
  `typeDoc` ENUM("i", "o") NULL,
  `dateDc` DATE NULL,
  PRIMARY KEY (`idDocLink`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonLink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PersonLink` (
  `idPersonLink` INT NOT NULL AUTO_INCREMENT,
  `idDoc` INT NULL,
  `typeDoc` ENUM("i", "o") NULL,
  `dateDc` DATE NULL,
  `idPerson` INT NULL,
  PRIMARY KEY (`idPersonLink`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SysTrfLink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SysTrfLink` (
  `idSysTrfLink` INT NOT NULL AUTO_INCREMENT,
  `idDoc` INT NULL,
  `typeDoc` ENUM("i", "o") NULL,
  `dateDc` DATE NULL,
  `idSysTrf` INT NULL,
  PRIMARY KEY (`idSysTrfLink`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AbonentLink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AbonentLink` (
  `idAbonentLink` INT NOT NULL AUTO_INCREMENT,
  `idDoc` INT NULL,
  `typeDoc` ENUM("i", "o") NULL,
  `dateDc` DATE NULL,
  `idAbonent` INT NULL,
  PRIMARY KEY (`idAbonentLink`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
